export { h } from './h'
export { renderSlots } from '../helper/renderSlots'
export { createTextVNode } from './vnode'
export { getCurrentInstance } from './components'
export { provide, inject } from './apiInject'
export { createRenderer } from './render'
